name:                bmctoy
version:             0.1.0.0
github:              "ksgm-of-ksgms/bmctoy"
license:             BSD3
author:              "ksgm"
maintainer:          "ksgm"
copyright:           "2020 ksgm"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/ksgm-of-ksgms/bmctoy#readme>

dependencies:
- base >= 4.7 && < 5
- generic-lens
- lens
- th-abstraction
- template-haskell
- containers
- sbv

library:
  source-dirs: src

executables:
  bmctoy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bmctoy

tests:
  bmctoy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bmctoy

default-extensions:
- TypeOperators
- TypeApplications

